### ISSUE TITLE
맛잘앗 홈페이지 스타일 작업 ( home/index )

### ISSUE THREAD

**Issue by wintersky2** [Matjalal/Matjalal#4]
## 작업 내용

- 홈 인덱스 페이지를 구현한다.

## Todo

- [x] app/home/index/page.tsx 페이지 라우팅

- [x] 테일윈드로 style 구현

![Image](https://github.com/Matjalal/Matjalal/assets/148525670/ab814207-e6e9-41a2-9a14-4c36b9e72328)

**Comment by wintersky2** [comment]
Tailwind 숙련도 부족으로 임시로 Figma로 대체함.

Tailwind를 익혀야함.

**Comment by TwinOgre** [comment]
https://codepen.io/TwinOgre/pen/abXWYLE

**Comment by TwinOgre** [comment]
## https://fonts.google.com/?subset=korean&noto.script=Kore

## https://velog.io/@mjieun/Next.js-Google-%ED%8F%B0%ED%8A%B8-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0
